import Head from 'next/head'
import Link from 'next/link';
// import styles from '@/styles/Home.module.css'


export default function Home() {
  
function questionAskedHandler(event) {
  event.preventDefault();
}  
  
  return (
    <>
      <Head>
        <title>Python 401 Final Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex items-center justify-between p-4 bg-gray-500 text-gray-50'>
        <h1> ONE STOP STREAM SPOT </h1>

      </header>
      <main>
        
          <div>
          <p className="text-center text-2xl"> What Services do you have?</p>
          </div>
        <div className="flex justify-center grid grid-rows-2 grid-flow-col gap-4 ">
          <div className="aspect-w-1">
            <p>Netflix</p>
            <img className=" object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/netflix_logo.png" alt='netflix'></img>
          </div>
          <div>
            <p>Hulu</p>
            <img className=" object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/hulu.png" alt='hulu'></img>
          </div>
          <div>
            <p>HBO Max</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/hbomax.png" alt='hbomax'></img>
          </div>
          <div>
            <p>Amazon Prime Video</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/amazonprime.jpeg" alt='amazonprimevideo'></img>
          </div>
          <div>
            <p>Disney+</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/disneyplus.png" alt='disneyplus'></img>
          </div>
          <div>
            <p>Peacock</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/peacock.jpeg" alt='peacock'></img>
          </div>
          <div>
            <p>Paramount+</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/paramountplus.png" alt='paramountplus'></img>
          </div>
          <div>
            <p>YouTube TV</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/youtube.png" alt='youtube'></img>
          </div>
        </div>
        <div>
          <button class="outline outline-offset-2 outline-1 ...">Button A</button>
          </div>
        <div className="text-center">
          <p className="text-center text-2xl"> What Genres do you prefer?</p>
        </div>
        <div className="flex justify-center grid grid-rows-2 grid-flow-col gap-4 ">
        <div className="flex justify-center grid grid-rows-2 grid-flow-col gap-4 ">
          <div className="aspect-w-1">
            <p>Action</p>
            <img className=" object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/action.png" alt='netflix'></img>
          </div>
          <div>
            <p>Comedy</p>
            <img className=" object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/comedy.png" alt='hulu'></img>
          </div>
          <div>
            <p>Documentary</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="assets/documentary.png" alt='hbomax'></img>
          </div>
          <div>
            <p>Drama</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="assets/drama.png" alt='amazonprimevideo'></img>
          </div>
          <div>
            <p>Fantasy</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/fantasy.png"></img>
          </div>
          <div>
            <p>Horror</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/horror.png" alt='peacock'></img>
          </div>
          <div>
            <p>Musical</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/music.png" alt='paramountplus'></img>
          </div>
          <div>
            <p>Mystery</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/detective.png" alt='youtube'></img>
          </div>
          <div>
            <p>Romance</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/romance.png" alt='youtube'></img>
          </div>
          <div>
            <p>Thriller</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/thriller.png" alt='youtube'></img>
          </div>
          <div>
            <p>Science Fiction</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="assets/sci-fi.png" alt='youtube'></img>
          </div>
          <div>
            <p>Western</p>
            <img className="object-fill h-40 w-96 ... w-16 md:w-32 lg:w-48" src="/assets/western.png" alt='youtube'></img>
          </div>
        </div>
        <div>
          <button class="outline outline-offset-2 outline-1 ...">Button A</button>
          </div> 
        </div>

      </main>
      <footer className='p-4 mt-8 bg-gray-500 text-gray-50'>
        <Link href="/about"> About
        </Link>

      </footer>
    </>
  )
}
